# API伺服器端口
web-port: 8080
# 玩家資料過濾
# 如果是正版服，會過濾盜版資料
# 如果是盜版服，則過濾正版資料
# 完成後會自動把過濾後的檔案放在壓縮檔。
# 記得過濾後把他關掉
filter: false
# 是否為正版服 ( 是則使用正版皮膚，非則使用盜版皮膚)
premium: true
# 玩家過濾列表
# 過濾不想出現在排行榜的玩家
filter-players:
  - Notch
  - md_5
  - Herobrine