# API伺服器端口
web-port: 8080
# 伺服器ID辨認 ( 排行榜顯示)
server-name: "1服"
# 玩家資料過濾
# 如果是正版服，會過濾盜版資料
# 如果是盜版服，則過濾正版資料
# 完成後會自動把過濾後的檔案放在壓縮檔。
# 記得過濾後把他關掉
filter: false
# 是否為正版服 (是則使用正版皮膚，非則使用盜版皮膚)
premium: true
# 默認皮膚顯示 (作為盜版服玩家時)
steve-uuid: "8667ba71-b85a-4004-af54-457a9734eed7"
# 玩家過濾列表
# 過濾不想出現在排行榜的玩家
filter-players:
  - Notch
  - md_5
  - Herobrine
# 檢測插件目前正在運行的狀態
# 洗屏注意!!!!!
debug: false